name: Generate Snake Animation (Pac-Man)

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Generate Pac-Man graph
        uses: Platane/snk@v3
        with:
          github_user_name: nar-en57
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Pac-Man graph"
          add: "output"

